module.exports = {
	verbs: ['purring with cats',
		'pooping out of fear',
		'running away from scary things',
		'swimming in swamps',
		'crying over fictional characters',
		'reading dirty fanfiction',
		'playing games',
		'destroying flowers',
		'gardening in peace',
		'teaching others',
		'sleeping all day',
		'thinking about Jonas',
		'robbing from the rich',
		'fucking ur mom all day lol get rekt',
		'casting spells',
		'flirting with everyone',
		'laughing at things that are not funny',
		'being a weeb',
		'telling lies about themselves',
		'eating mass amounts of instant ramen',
		'starving to death',
		'baking cookies',
		'smiling creepily at strangers',
		'staring into your soul',
		'travelling across the world',
		'sending people memes',
		'sailing across the ocean',
		'pouring themselves an excessive amount of alcohol',
		'passing out from drinking all night',
		'mimicking frogs',
		'smoking that dank weed 420 blaze it',
		'riding away into the sunset',
		'fighting bad guys',
		'complimenting others',
		'gathering treasure',
		'insulting others',
		'pointing at others inconsiderately',
		'wearing glasses',
		'singing showtunes',
		'feeling loved',
		'finding deep dark secrets',
		'pretending to know everything',
		'petting cats',
		'trying their best',
		'knitting scarves for others',
		'howling at the moon',
		'relaxing at home'
	],
	nouns1: ['girl',
		'boy',
		'human',
		'alien',
		'man',
		'woman',
		'male',
		'female',
		'elf',
		'orc',
		'kappa',
		'mermaid',
		'griffin',
		'unicorn',
		'dragon',
		'phoenix',
		'centaur',
		'minotaur',
		'harpy',
		'werewolf',
		'siren',
		'cyclops',
		'gorgon',
		'chimera',
		'fenrir',
		'cat s�th',
		'vampire',
		'selkie',
		'tengu',
		'hellhound',
		'gargoyle',
		'ghost',
		'satyr',
		'incubus',
		'fairy',
		'goblin',
		'undine',
		'succubus',
		'witch',
		'wizard',
		'nymph',
		'ent',
		'foo dog',
		'kirin',
		'gnome',
		'warg',
		'zombie',
		'slime',
		'basilisk',
		'cat-girl',
		'cat-boy',
		'moth-girl',
		'moth-boy',
		'yokai',
		'Jonas',
		'kitsune',
		'oni',
		'warrior',
		'fighter',
		'knight',
		'paladin',
		'barbarian',
		'berzerker',
		'monk',
		'martial artist',
		'archer',
		'ranger',
		'thief',
		'rogue',
		'assassin',
		'priest',
		'healer',
		'mage',
		'summoner',
		'necromancer',
		'pirate',
		'dragon knight',
		'samurai',
		'druid',
		'shaman',
		'gambler',
		'bard',
		'bandit',
		'ninja',
		'scout',
		'witch doctor',
		'templar',
		'beast master',
		'dancer',
		'magic knight',
		'engineer',
		'gunslinger',
		'alchemist',
		'psychic',
		'puppet master',
		'spy',
		'shapeshifter'
	],
	nouns2: ['coat',
		'dress',
		'skirt',
		'sweater',
		'cape',
		'belt',
		'armor',
		'corset',
		'robe',
		'cloak',
		'hat',
		'booties',
		'gloves',
		't-shirt',
		'pyjamas',
		'bikini',
		'cardigan',
		'cat kigurumi',
		'jacket',
		'kilt',
		'lingerie',
		'poncho',
		'scarf',
		'socks',
		'panties',
		'vest',
		'bag',
		'hijab',
		'pants',
		'overcoat',
		'scrubs',
		'peacoat',
		'petticoat',
		'highwaisted pants',
		'highwaisted skirt',
		'crop top',
		'virgin-killer sweater',
		'key-hole sweater',
		'tank top',
		'bra',
		'sandals',
		'running shoes',
		'thigh-high boots',
		'toesocks',
		'cat ears',
		'fox tail',
		'bucket hats with meme buttons'
	],
	nouns3: ['cats',
		'babies',
		'lions',
		'tigers',
		'bears',
		'books',
		'dogs',
		'computers',
		'coffee',
		'tea',
		'spaghetti',
		'veggies',
		'fruit',
		'plants',
		'love',
		'life',
		'school',
		'hair',
		'eyes',
		'milk',
		'friends',
		'art',
		'boys',
		'girls',
		'Jonas',
		'memes',
		'magic',
		'stories',
		'sex',
		'food',
		'diamonds',
		'dinosaurs',
		'math',
		'feet',
		'internal organs',
		'music',
		'blood',
		'flowers',
		'pizza',
		'planets',
		'stars',
		'socks',
		'ants',
		'pianos',
		'cartoons',
		'chess'
	],
	adjs1: ['adorable ',
		'beautiful',
		'clean',
		'drab',
		'elegant',
		'fancy',
		'glamourous',
		'handsome',
		'long',
		'magnificent',
		'old-fashioned',
		'plain',
		'quaint',
		'sparkling',
		'ugly',
		'unsightly',
		'wide-eyed',
		'red',
		'orange',
		'yellow',
		'green',
		'blue',
		'purple',
		'black',
		'white',
		'brown',
		'cream',
		'pastel',
		'mint',
		'teal',
		'striped',
		'spotted',
		'alive',
		'dead',
		'powerful',
		'rich',
		'shy',
		'brave',
		'calm',
		'eager',
		'gentle',
		'happy',
		'jolly',
		'proud',
		'angry',
		'clumsy',
		'embarrassed',
		'fierce',
		'itchy',
		'lazy',
		'nervous',
		'anxious',
		'scary',
		'little',
		'chubby',
		'petite',
		'short',
		'tall',
		'giant',
		'hissing',
		'noisy',
		'purring',
		'whispering',
		'ancient',
		'modern',
		'slow',
		'young',
		'old',
		'dirty',
		'dusty',
		'fluffy',
		'mysterious',
		'alluring',
		'demonic',
		'foolish',
		'grey',
		'hungry',
		'envious',
		'childish',
		'lewd',
		'lush',
		'macabre',
		'malicious',
		'na�ve',
		'nostalgic',
		'obedient',
		'odd',
		'pale',
		'pink',
		'poor',
		'magical',
		'monsterous',
		'quirky',
		'royal',
		'tired',
		'sneaky',
		'stinky'
	],
	adjs2: ['cute',
		'baggy',
		'casual',
		'loose',
		'tight',
		'comfortable',
		'grungy',
		'old',
		'formal',
		'heavy',
		'red',
		'orange',
		'yellow',
		'blue',
		'purple',
		'black',
		'white',
		'brown',
		'cream',
		'pastel',
		'mint',
		'teal',
		'gret',
		'striped',
		'spotted',
		'hooded',
		'itchy',
		'light',
		'long',
		'modest',
		'knit',
		'cotton',
		'chiffon',
		'wool',
		'soft',
		'velvet',
		'shredded',
		'sexy',
		'chic',
		'hairy',
		'plain',
		'thin',
		'see-through',
		'sheer',
		'leather',
		'denim',
		'frilly'
	]
};
